# Generated by Django 6.0.3 on 2026-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
