# Generated by Django 6.0.3 on 2026-03-20 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_sessions", "0002_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="ticket_code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
